name: Alberto Resume
favicon: null
layout_spectrum: 0.4432459950912744
typography_spectrum: 0.8050320951733738
title: Resume
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6901190131902695
  lightness: 0.8913038966711611
  saturation: 0.26370966201648116
  rhythmicContrast: 0.7993572338018566
purpose: []
